from dataclasses import dataclass
from datetime import datetime


@dataclass
class Dataprovider:
    continent: str
    country: str
    region: str
    zipcode: str
    zipcodequality: int
    city: str
    address: str
    addresses: str
    company: str
    companytype: str
    companyquality: int
    legalentity: str
    cocnumber: str
    bankaccountnumber: str
    iban: str
    bic: str
    taxnumber: str
    phonenumber: str
    phonenumberquality: int
    phonenumbers: str
    emailaddress: str
    emailaddresses: str
    contactable: list[str]
    employee: str
    response: str
    title: str
    description: str
    keywords: str
    relevantkeywords: str
    features: list[str]
    wordcount: int
    developed: bool
    type: str
    category: str
    siccode: int
    sicmajorgroup: str
    sicdivision: str
    naicscode: int
    copyright: int
    creator: str
    creatorhostname: str
    logo: str
    language: str
    multilanguage: bool
    metaauthors: str
    privacysensitive: bool
    pages: int
    pagesindexed: int
    pagetypes: list[str]
    htmlsize: int
    dateadded: datetime
    since: datetime
    date: datetime
    manual: datetime
    dateremoved: datetime
    websiteage: int
    websitestate: str
    ecommerce: bool
    ecommercequality: int
    brickandmortar: bool
    brickandmortarprobability: int
    scs: str
    trustmarks: list[str]
    delivery: list[str]
    paymentmethods: list[str]
    psp: list[str]
    currency: str
    pricerange: int
    products: int
    eii: int
    activity: str
    changes: int
    changedfields: list[str]
    trustgrade: str
    cloudscore: int
    securityscore: int
    incominglinks: int
    outgoinglinks: int
    visitors: int
    visitorsavg: int
    trafficindex: int
    twitterfollowers: int
    twitterfollowing: int
    instagramfollowers: int
    instagramfollowing: int
    facebookfollowers: int
    analyticsid: str
    adsenseid: str
    brandnames: list[str]
    analytics: list[str]
    advertisements: list[str]
    affiliates: list[str]
    socialplatforms: list[str]
    social: list[str]
    socialprofiles: str
    livechat: list[str]
    crm: str
    emailservices: str
    chainid: str
    chaincount: int
    other: str
    tldsuggestions: list[str]
    cms: str
    scriptinglanguage: str
    grade: float
    seo: int
    seosummary: str
    flash: bool
    doctype: str
    generator: str
    mobile: bool
    mobileapp: list[str]
    maps: list[str]
    libraries: list[str]
    renderedhostnames: list[str]
    renderedlogos: list[str]
    renderedcookiehostnames: list[str]
    scanrequestid: int
    hostname: str
    tld: str
    tldtype: str
    gtldcategory: str
    subdomain: str
    domain: str
    domainlength: int
    zone: bool
    idn: bool
    idnparts: list[str]
    subdomains: list[str]
    subdomainscount: int
    resolvedsubdomains: list[str]
    resolvedasnumbers: list[str]
    resolvedipscount: int
    redirecthostname: str
    redirecttld: str
    forwarding: list[str]
    forwardingcount: int
    hostingcountry: str
    ip: str
    ipv6: str
    alternativeips: str
    asnumber: int
    ascompany: str
    registrar: str
    reseller: str
    whoisname: str
    whoisorganization: str
    whoisaddress: str
    whoiszip: str
    whoiscity: str
    whoiscountry: str
    whoisphone: str
    whoisemail: str
    whoiscreation: str
    whoisexpiration: str
    whoisupdated: str
    whoisianaid: int
    nameserver: str
    dnsns: list[str]
    mxdomain: str
    dnstxt: list[str]
    dnssec: bool
    dnscname: str
    os: str
    webserver: str
    websiteheaders: str
    openports: list[str]
    openportscount: int
    controlpanel: str
    serversignature: str
    ssl: bool
    sslissuerorganization: str
    ssldomaintype: str
    sslissuercommonname: str
    sslstartdate: datetime
    sslenddate: datetime
    sslalgorithm: str
    ssltype: str
    statuscodes: list[str]
    loadtime: int
    cdn: list[str]
    video: list[str]
    parking: str
    placeholder: str
